### ISSUE TITLE
Fix travis setup

### ISSUE THREAD

**Issue by pieterdavid** [cp3-llbb/plotIt#102]
The [travis job](https://travis-ci.org/cp3-llbb/plotIt/builds/429495213) for https://github.com/cp3-llbb/plotIt/pull/101 failed with:
`The command "wget http://sbrochet.web.cern.ch/sbrochet/public/ROOT-${ROOT_VERSION}_Python-2.7_Ubuntu-12.04_gcc4.9.tar.xz" failed and exited with 4 during`.
I'll try to have a look at building a new package ([this](https://github.com/rootpy/travis-ci-root-builds) seems like a recipe, does anyone remember if @blinkseb used this or something else?), but any ideas/suggestions are welcome.

**Comment by delaere** [comment]
Oops.
We had anticipated that and moved everything to http://cp3.irmp.ucl.ac.be/~delaere/MoMEMta/ but apparently we forgot to change the travis job itself.

**Comment by delaere** [comment]
By the way, Pavel did something else to achieve the same goal for Delphes: he's running docker on travis. So he just has to provide docker images for various platforms, and that's done by uploading the docker image to dockerhub. This removes the need for public files on a private home.

**Comment by pieterdavid** [comment]
Thanks, I found the urls in the MoMEMta travis scripts, I'll use these. (using docker with travis-ci.org is possible, but not the most elegant solution, so I'd stick to this solution for now. Delphes seems to use something else, circleci)

**Comment by pieterdavid** [comment]
For completeness (and future updates): is the script that was used to build the ROOT packages saved somewhere?

**Comment by pieterdavid** [comment]
Answering my own question above: https://github.com/pieterdavid/travis-ci-root-builds should work (I built a ROOT 6.14.04 tarball in docker to test)
