### ISSUE TITLE
UUID does not work on SLC6

### ISSUE THREAD

**Issue by swertz** [cp3-llbb/plotIt#107]
PlotIt uses Linux's built-in UUID definitions, which seem to have changed since Linux 3, so it works fine on ingrid's and lxplus CC7/SLC7, but for centres that are stuck in the middle ages there's no way to build it.

Since we link with boost anyway one solution would be to change to use boost::uuid. 

Opinions?

What surprises me is that it worked fine in 2015/2016 when ingrid was still running SLC6...

**Comment by pieterdavid** [comment]
I think I compiled it a few months ago on SLC6 (ingrid-ui2) still without problems... no objection to changing to the boost one, though (keep in mind that boost on SLC6 is quite ancient too, and the CMS-bundled one only slightly less so, iirc - but the uuid library probably hasn't changed much recently). For my curiosity: why does plotIt actually need uuid?

**Comment by swertz** [comment]
Ok, it looks like UI2 uses Linux 3.1 while the machine I have to work on has Linux 2.6 :1st_place_medal: 

It seems it's used as an index in a map to cache the histograms (and to name the histograms created with `TTree:Draw` in "tree" mode): https://github.com/cp3-llbb/plotIt/blob/master/src/plotIt.cc#L1549,L1588
