### ISSUE TITLE
Legends

### ISSUE THREAD

**Issue by BrieucF** [cp3-llbb/plotIt#18]
- [x] For plots in pdf, text in legend such as 'X2 \to HH (260)' are not displayed (but the legend entry is visible)
- [x] Once we use groups some legends disapear. It seems that this problem appears from commit #14. We will try to provide more details on this issue soon.

**Comment by blinkseb** [comment]
1) Can you try with 'X2 #to HH (260)' for the legend (`#` instead of `\`). It seems that `\` enforce the use of `TMathText` but it's not supported in PDF.

 2) I'll look at it ASAP. If you can point me to your config file it'd be really useful :+1:

**Comment by swertz** [comment]
For 2), you can try it out with the configs in /home/fynu/swertz/scratch/CMSSW_7_4_15/src/cp3_llbb/plotIt/test/TTAnalysis ;) There are two groups: data and tW. Data doesn't cause any problem, but as soon as the group tW is used, the legend becomes a bit moody...

**Comment by blinkseb** [comment]
At least I'm able to reproduce and indeed, it's not working as expected :smile:

**Comment by BrieucF** [comment]
The #to gives "#to" but #rightarrow works, thanks :-)
