### ISSUE TITLE
Empty bins need errors bars

### ISSUE THREAD

**Issue by OlivierBondu** [cp3-llbb/plotIt#54]
yes, I know... but recommendations:
https://twiki.cern.ch/twiki/bin/view/CMS/PoissonErrorBars

**Comment by blinkseb** [comment]
Hm, errors are poisson by default, so you should have errors bar for empty bins also. It's not working?

**Comment by OlivierBondu** [comment]
is the poisson error recomputed ? something to do with root default being two sided CI for non-empty but one-sided CI for empty bins
(aka error for empty bin should be around 1.8 not 1.2)

sorry if I missed this commit :(

**Comment by blinkseb** [comment]
It was introduced by 908e0c3bf6f5b464da589e65c12366b08d6dc014, so it's exactly what is written on the twiki (`h1->SetBinErrorOption(TH1::kPoisson);`). But maybe the drawing is done with `E` and not `E0` so error bars for empty are not drawn? I'll check

**Comment by OlivierBondu** [comment]
no no, sorry, all good, closing this and sorry for the noise !

**Comment by OlivierBondu** [comment]
thanks !
